# encoding: UTF-8
#<% require 'kitchen-sync' %>
---
driver:
  name: docker
driver_config:
  require_chef_omnibus: true

provisioner:
  name: chef_zero
  attributes:
    authorization:
      sudo:
        users: ['kitchen']
        passwordless: true
    garcon:
      civilize:
        dotfiles:
          - root
          - kitchen

platforms:
  - name: ubuntu-14.04
    run_list:
    - recipe[apt]
  - name: centos-6.6
    run_list:
    - recipe[yum]
  - name: centos-7.1
    run_list:
    - recipe[yum]

suites:
  - name: default
    run_list:
      - recipe[test_fixtures::default]
