# encoding: UTF-8
#<% require 'kitchen-sync' %>
---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: true

platforms:
  - name: centos-6
  - name: centos-7
  - name: fedora-21
  - name: ubuntu-12.04
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[test_fixtures::default]
